### ISSUE TITLE
Original Noto issues to fix in new version

### ISSUE THREAD

**Issue by joanaranito** [universalthirst/noto-bengali#2]
- [x] Fix shape of tt_ra-beng: https://github.com/notofonts/bengali/issues/21
- [x] Remove bengali half-forms: https://github.com/notofonts/bengali/issues/10
- [x] Address h_nna and k_ss_nna: https://github.com/notofonts/bengali/issues/5.  Add stylistic set for nna shapes in h_nna and k_ss_nna? See: https://github.com/TiroTypeworks/Indigo/issues/30#issuecomment-1195690776
- [x] Make sure all ba conjuncts have a wa variant for Pali: https://github.com/notofonts/bengali/issues/1 
- [x] Make sure Pali conjuncts are not activated for Assamese, by adding locl feature with PAL language tag, and/or stylistic set
